upstreamProjects:
  Mule-runtime/mule-extensions-parent/support/1.9.x,
  Mule-runtime/mule-http-service/1.11.0-DRY-RUN,
  Mule-runtime/mule-oauth-service/2.6.0-DRY-RUN,
  Mule-runtime/mule-scheduler-service/1.9.0-DRY-RUN,
  Mule-runtime/mule-soap-service/1.8.1-DRY-RUN
projectType: runtime
enableMavenTestStage: false
