upstreamProjects:
  Mule-runtime/mule-extensions-parent/1.8.3,
  Mule-runtime/mule-http-service/1.10.3,
  Mule-runtime/mule-oauth-service/2.5.3,
  Mule-runtime/mule-scheduler-service/1.8.3,
  Mule-runtime/mule-soap-service/1.8.3
projectType: runtime
enableMavenTestStage: false
