upstreamProjects:
  Mule-runtime/mule-extensions-parent/1.8.3-DRY-RUN,
  Mule-runtime/mule-http-service/1.10.3-DRY-RUN,
  Mule-runtime/mule-oauth-service/2.5.3-DRY-RUN,
  Mule-runtime/mule-scheduler-service/1.8.3-DRY-RUN,
  Mule-runtime/mule-soap-service/1.8.3-DRY-RUN
projectType: runtime
enableMavenTestStage: false
