upstreamProjects:
  Mule-runtime/mule-extensions-parent/support/1.9.x,
  Mule-runtime/mule-http-service/1.11.0-DRY-RUN,
  Mule-runtime/mule-oauth-service/support/2.6.x,
  Mule-runtime/mule-scheduler-service/support/1.9.x,
  Mule-runtime/mule-soap-service/support/1.9.x
projectType: runtime
enableMavenTestStage: false
