upstreamProjects:
  Mule-runtime/mule-extensions-parent/1.6.11-DRY-RUN,
  Mule-runtime/mule-http-service/1.8.11-DRY-RUN,
  Mule-runtime/mule-oauth-service/2.3.11-DRY-RUN,
  Mule-runtime/mule-scheduler-service/1.6.11-DRY-RUN,
  Mule-runtime/mule-soap-service/1.6.11-DRY-RUN
projectType: runtime
enableMavenTestStage: false
