upstreamProjects:
  Mule-runtime/mule-extensions-parent/support/1.9.x,
  Mule-runtime/mule-http-service/1.11.0,
  Mule-runtime/mule-oauth-service/2.6.0,
  Mule-runtime/mule-scheduler-service/1.9.0,
  Mule-runtime/mule-soap-service/1.8.1
projectType: runtime
enableMavenTestStage: false
